baseurl = "/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "10"
title = "San Diego Hood Cleaning Pros"
[Params]
authorbox = true
description = "We will cleaning anything in your professional kitchen!"
opengraph = true
postSections = ["post"]
post_navigation = true
readmore = false
subtitle = "(555) 555-5555"
twitter_cards = false
[Params.widgets]
recent_num = 5
tags_counter = false
[[menu.main]]
name = "Test"
url = "https://sandiegohoodcleaningpros.com/test"
weight = 5
