baseurl = "https://sandiegohoodcleaningpros.com"
languageCode = "en-us"
title = "Restaurant Hood Cleaning Services San Diego, California"
canonifyUrls = "true"
theme = "hoods"

[params]
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:bushbama@whitehouse.gov"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/in/yourusername"
