baseurl = "/"
title = "San Diego Hood Cleaning Pros"
languageCode = "en-us"
paginate = "10" # Number of posts per page
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params]
  subtitle = "(555) 555-5555" # Subtitle of your site
  description = "We will cleaning anything in your professional kitchen!" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  postSections = ["post"]


[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
  
